trigger:
- master

resources:
  repositories:
  - repository: helmRepo
    type: github
    endpoint: John D Watson
    name: johnwatson484/helm-charts

pool:
  vmImage: 'ubuntu-latest'

variables:
  repo: kubernetes-test-app
  helmRepo: helm-charts
  helmRepositoryUrl: git@github.com:johnwatson484/helm-charts.git
  version:
  containerRepository: johnwatson484/kubernetes-test-app
  helmChartPath: helm/kubernetes-test-app

steps: 
  - checkout: self

  - task: PowerShell@2
    displayName: Set version
    inputs:
      targetType: 'inline'
      script: |
        $packageVersion = (Get-Content '$(Agent.BuildDirectory)/s/$(repo)/package.json' | ConvertFrom-Json).version
        Write-Host "##vso[task.setvariable variable=version;]$packageVersion"

  # - task: Docker@2
  #   displayName: Build image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'build'
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false

  # - task: Docker@2
  #   displayName: Push image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'push'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false
  
  - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 'latest'

  - checkout: helmRepo

  - script: |
      helm package $(Agent.BuildDirectory)/s/$(repo)/$(helmChartPath) --version $(version) --destination $(Agent.BuildDirectory)/s/$(helmRepo)
    displayName: Package Helm

  - task: InstallSSHKey@0
    displayName: Install deploy key
    inputs:
      knownHostsEntry: 'github.com'
      sshPublicKey: 'PK'
      sshKeySecureFile: 'GitHub-Helm-Deploy-Key'
  
  - script: |
      cd $(Agent.BuildDirectory)/s/$(helmRepo)
      helm repo index . --merge ./index.yaml
      git config --global user.email "azuredevops@microsoft.com"
      git config --global user.name "Azure DevOps"
      git remote set-url --push origin $(helmRepositoryUrl)
      git add .
      git commit -m "$(repo) updated by Azure DevOps"
      git push origin HEAD:master
    displayName: Update Helm repo

  