# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  version:
  containerRepository: johnwatson484/kubernetes-test-app

steps: 
  - task: PowerShell@2
    displayName: Set version
    inputs:
      targetType: 'inline'
      script: |
        $packageVersion = (Get-Content 'package.json' | ConvertFrom-Json).version
        Write-Host "##vso[task.setvariable variable=version;]$packageVersion"

  

  # - task: Docker@2
  #   displayName: DockerHub login
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     command: 'login'
  #     addPipelineData: false

  # - task: DockerCompose@0
  #   inputs:
  #     containerregistrytype: 'Container Registry'
  #     dockerRegistryEndpoint: 'DockerHub'
  #     dockerComposeFile: '**/docker-compose.yaml'
  #     buildImages: 
  #     action: 'Build services'
  #     additionalImageTags: '$(version)'
  #     includeLatestTag: true
  
  # # - task: DockerCompose@0
  # #   displayName: Push image
  # #   inputs:
  # #     containerregistrytype: 'Container Registry'
  # #     dockerRegistryEndpoint: 'DockerHub'
  # #     dockerComposeFile: '**/docker-compose.yaml'
  # #     projectName: '$(repository)'
  # #     action: 'Push services'
  # #     additionalImageTags: '$(version)'
  # #     includeLatestTag: true

  # - task: Docker@2
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(repository)'
  #     command: 'push'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false

  - task: Docker@2
    displayName: Build image
    inputs:
      containerRegistry: 'DockerHub'
      repository: '$(containerRepository)'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(version)
        latest
      addPipelineData: false

  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: 'DockerHub'
      repository: '$(containerRepository)'
      command: 'push'
      tags: |
        $(version)
        latest
      addPipelineData: false