# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  version:
  containerRepository: johnwatson484/kubernetes-test-app
  helmChartPath: ./helm/kubernetes-test-app
  helmRepository: 

steps: 
  - task: PowerShell@2
    displayName: Set version
    inputs:
      targetType: 'inline'
      script: |
        $packageVersion = (Get-Content 'package.json' | ConvertFrom-Json).version
        Write-Host "##vso[task.setvariable variable=version;]$packageVersion"

  # - task: Docker@2
  #   displayName: Build image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'build'
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false

  # - task: Docker@2
  #   displayName: Push image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'push'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false
  
  - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 'latest'

  - script: |
      mkdir helm-repo
      cd helm-repo
      git clone https://github.com/johnwatson484/helm-charts.git
    displayName: Clone Helm repo

  - task: HelmDeploy@0
    displayName: Package Helm
    inputs:
      command: 'package'
      chartPath: '$(helmChartPath)'
      destination: './helm-repo'
      arguments: '--version $(version)'

  - script: |
      cd helm-repo
      helm index . --merge ./index.yaml
      git add .
      git commit -m "$(helmChartPath) updated by Azure DevOps"
      git push
    displayName: Update Helm repo