# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  version:
  repository: johnwatson484/kubernetes-test-app

steps: 
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $packageVersion = (Get-Content 'package.json' | ConvertFrom-Json).version
        Write-Host "##vso[task.setvariable variable=version;]$packageVersion"
    displayName: Set version

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      command: 'login'
      addPipelineData: false
    displayName: DockerHub login

  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      dockerComposeFile: '**/docker-compose.yaml'
      action: 'Build services'
      additionalImageTags: '$(version)'
      includeLatestTag: true
    displayName: Build image
  
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: '**/docker-compose.yaml'
      action: 'Push services'
      additionalImageTags: '$(version)'
      includeLatestTag: true
    displayName: Push image
