trigger:
- master

resources:
  repositories:
  - repository: helmRepo
    type: github
    endpoint: John D Watson
    name: johnwatson484/helm-charts

pool:
  vmImage: 'ubuntu-latest'

variables:
  version:
  containerRepository: johnwatson484/kubernetes-test-app
  helmChartPath: helm/kubernetes-test-app
  helmRepository: https://github.com/johnwatson484/helm-charts.git

steps: 
  - checkout: self

  - task: PowerShell@2
    displayName: Set version
    inputs:
      targetType: 'inline'
      script: |
        $packageVersion = (Get-Content '$(Agent.BuildDirectory)/self/package.json' | ConvertFrom-Json).version
        Write-Host "##vso[task.setvariable variable=version;]$packageVersion"

  # - task: Docker@2
  #   displayName: Build image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'build'
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false

  # - task: Docker@2
  #   displayName: Push image
  #   inputs:
  #     containerRegistry: 'DockerHub'
  #     repository: '$(containerRepository)'
  #     command: 'push'
  #     tags: |
  #       $(version)
  #       latest
  #     addPipelineData: false
  
  - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 'latest'

  - checkout: helmRepo

  - script: |
      helm package $(Agent.BuildDirectory)/self/$(helmChartPath) --version $(version) --destination $(Agent.BuildDirectory)/helmRepo
    displayName: Package Helm
  
  - script: |
      cd $(Agent.BuildDirectory)/helmRepo
      helm repo index . --merge ./index.yaml
      git config --global user.email "ado@microsoft.com"
      git config --global user.name "Azure DevOps"
      git add .
      git commit -m "$(helmChartPath) updated by Azure DevOps"
      git push origin master
    displayName: Update Helm repo