apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ quote .Values.name }}
  labels: {{ include "kubernetes-test-app.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ quote .Values.name }}
  template:
    metadata:
      labels: {{ include "kubernetes-test-app.labels" . | trimSuffix "\n" | indent 6 }}
      annotations:
        linkerd.io/inject: {{ quote .Values.deployment.linkerdInject }}
        redeployOnChange: {{ quote .Values.deployment.redeployOnChange }}
    spec:
      securityContext:
        runAsUser: {{ .Values.deployment.runAsUser }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot }}
      restartPolicy: {{ quote .Values.deployment.restartPolicy }}
      containers:
      - name: {{ quote .Values.name }}
        image: {{ quote .Values.image }}
        imagePullPolicy: {{ quote .Values.container.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        env:
        - name: NODE_ENV
          value: {{ quote .Values.environment }}
        - name: PORT
          value: {{ quote .Values.container.port }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
          protocol: TCP
        resources:
          requests:
            memory: {{ quote .Values.container.requestMemory }}
            cpu: {{ quote .Values.container.requestCpu }}
          limits:
            memory: {{ quote .Values.container.limitMemory }}
            cpu: {{ quote .Values.container.limitCpu }}
